@baseUrl = http://waygookteacher.com/api/
// @baseUrl = http://127.0.0.1:8080/

### Login a registered User
POST {{baseUrl}}controllers/login.php HTTP/1.1

{
  "email": "kim_subin@gmail.com",
  "password": "password"
}

### Register a new user
POST {{baseUrl}}controllers/register.php HTTP/1.1
content-type: application/json

{
  "first": "Tom",
  "last": "Brady",
  "email": "tombrady9913339@gmail.com",
  "password": "PassWord!",
  "confirm": "PassWord!",
  "role": "teacher"
}

### Fetch a Profile
POST {{baseUrl}}controllers/profile.php HTTP/1.1

{
  "userID": 20
}

### Fetch all teachers
GET {{baseUrl}}controllers/teachers.php HTTP/1.1

### Update user settings/profile
POST {{baseUrl}}controllers/settings.php HTTP/1.1
content-type: application/json

{
  "userID": 20,
  "nationality": "English",
  "DOB": "1992-02-05",
  "timezone": "Perth/Korea"
}

### Upload profile image
POST {{baseUrl}}controllers/uploadImage.php HTTP/1.1

{
  "userID": 20,
  "uid": "123456789",
  "name": "fake_image.jpg",
  "extension": "image/jpeg",
  "type": "jpeg",
  "size": 25000
}

### Send a message
POST {{baseUrl}}controllers/sendMessage.php HTTP/1.1

{
  "text": "This is a RESTClient test!",
  "fromUserID": 23,
  "toUserID": 20
}

### Get all contacts (users with message history)
POST {{baseUrl}}controllers/inbox.php

{
  "userID": 20
}

### Get a specific conversation
POST {{baseUrl}}controllers/conversation.php

{
  "thisUserID": "20",
  "otherUserID": 31
}